# Generated by Django 5.0.6 on 2024-07-17 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment_comment', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_first_name', models.CharField(max_length=50)),
                ('customer_last_name', models.CharField(max_length=50)),
                ('customer_email', models.EmailField(max_length=254, unique=True)),
                ('customer_phone_number', models.CharField(max_length=12)),
                ('is_faculty_or_staff', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Dependent',
            fields=[
                ('dependent_id', models.AutoField(primary_key=True, serialize=False)),
                ('dependent_age', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PickupLocation',
            fields=[
                ('pickup_location_id', models.AutoField(primary_key=True, serialize=False)),
                ('pickup_location_name', models.CharField(max_length=50)),
                ('pickup_location_address', models.CharField(max_length=20)),
                ('pickup_location_description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=150)),
                ('product_description', models.TextField()),
                ('product_availability', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('product_quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('staff_first_name', models.CharField(max_length=50)),
                ('staff_last_name', models.CharField(max_length=50)),
                ('staff_position', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Demographics',
            fields=[
                ('demographics_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_secondary_email', models.EmailField(max_length=254, null=True, unique=True)),
                ('customer_NUID', models.CharField(default='0', max_length=20, null=True)),
                ('customer_grad', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('customer_affiliation', models.CharField(max_length=50, null=True)),
                ('is_international_student', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('is_first_gen', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('customer_class_standing', models.CharField(choices=[('1', 'Freshman'), ('2', 'Sophomore'), ('3', 'Junior'), ('4', 'Senior')], max_length=1, null=True)),
                ('customer_occupation', models.CharField(max_length=50)),
                ('customer_living_status', models.CharField(max_length=200)),
                ('customer_transportation', models.CharField(max_length=150)),
                ('customer_employment', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('customer_ethnicity', models.CharField(max_length=50)),
                ('customer_age', models.CharField(max_length=2)),
                ('customer_gender_identity', models.CharField(max_length=100)),
                ('customer_marital_status', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('customer_household_size', models.CharField(max_length=50)),
                ('has_dependents', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('customer_number_dependents', models.CharField(max_length=50, null=True)),
                ('customer_wgec', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('customer_zip_code', models.CharField(max_length=10)),
                ('customer_allergies', models.CharField(max_length=50)),
                ('comment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.comment')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.customer')),
                ('dependent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.dependent')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='demographics_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.demographics'),
        ),
        migrations.CreateModel(
            name='OrdersHeader',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateField()),
                ('order_fill_or_shop', models.CharField(max_length=20)),
                ('is_bag_required', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('order_fulfillment_date', models.DateField()),
                ('order_pickup_status', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('order_notification_date_1st', models.DateField(blank=True, null=True)),
                ('order_notification_date_2nd', models.DateField(blank=True, null=True)),
                ('order_notification_date_3rd', models.DateField(blank=True, null=True)),
                ('order_diapers', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('order_parent_supplies', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.customer')),
                ('pickup_location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.pickuplocation')),
            ],
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_line_number', models.CharField(max_length=100)),
                ('order_quantity_requested', models.CharField(max_length=100)),
                ('order_notes', models.TextField(blank=True, null=True)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.ordersheader')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.products')),
            ],
        ),
    ]
